'use strict';
const APP=Object.freeze({SPREADSHEET_NAME:'Dev.Sitampu',USER_SHEET_NAME:'User',CHAT_SHEET_NAME:'Chat',NOTIFICATION_SHEET_NAME:'Notifikasi',SESSION_TTL_SECONDS:21600,CHAT_TTL_MS:24*60*60*1000,USER_HEADERS:['Username','Password','Nama','Jabatan','Instansi'],CHAT_HEADERS:['ID','Pengirim','Penerima','Pesan','Waktu','Dibaca'],NOTIFICATION_HEADERS:['ID','Username','Tipe','Judul','Pesan','Waktu','Dibaca','Referensi']});
function doGet(){return jsonResponse({success:true,message:'API Si-Tampu aktif',spreadsheet:APP.SPREADSHEET_NAME});}
function doPost(e){try{const r=JSON.parse((e&&e.postData&&e.postData.contents)||'{}'),a=String(r.action||'').trim();if(a==='login')return jsonResponse(loginUser(r));const s=validateToken(r.token);if(!s.valid)return jsonResponse({success:false,auth:false,sessionExpired:true,message:'Sesi tidak valid atau telah berakhir.'});switch(a){case'validateSession':return jsonResponse({success:true,user:s.user});case'logout':return jsonResponse(logoutUser(r.token));case'getUsers':requireAdmin(s.user);return jsonResponse({success:true,users:getUsers()});case'addUser':requireAdmin(s.user);return jsonResponse(addUser(r,s.user));case'editUser':requireAdmin(s.user);return jsonResponse(editUser(r,s.user));case'deleteUser':requireAdmin(s.user);return jsonResponse(deleteUser(r,s.user));case'getChatUsers':return jsonResponse({success:true,users:getChatUsers(s.user)});case'getChats':return jsonResponse(getChats(s.user,r.withUser));case'sendChat':return jsonResponse(sendChat(s.user,r));case'getNotifications':return jsonResponse(getNotifications(s.user));case'markNotificationRead':return jsonResponse(markNotificationRead(s.user,r.id));case'markAllNotificationsRead':return jsonResponse(markAllNotificationsRead(s.user));default:return jsonResponse({success:false,message:'Action tidak dikenali.'});}}catch(err){return jsonResponse({success:false,message:err.message||'Terjadi kesalahan pada server.'});}}
function getSpreadsheet(){const files=DriveApp.getFilesByName(APP.SPREADSHEET_NAME);if(!files.hasNext())throw new Error('Spreadsheet "'+APP.SPREADSHEET_NAME+'" tidak ditemukan.');const file=files.next();if(files.hasNext())throw new Error('Nama spreadsheet lebih dari satu.');return SpreadsheetApp.open(file);}
function getSheet(name,headers){const ss=getSpreadsheet();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);}return sh;}
function getUserSheet(){return getSheet(APP.USER_SHEET_NAME,APP.USER_HEADERS);}function getChatSheet(){return getSheet(APP.CHAT_SHEET_NAME,APP.CHAT_HEADERS);}function getNotificationSheet(){return getSheet(APP.NOTIFICATION_SHEET_NAME,APP.NOTIFICATION_HEADERS);}
function loginUser(r){const username=normalize(r.username),password=String(r.password||'');if(!username||!password)return{success:false,message:'Username dan password wajib diisi.'};const found=readUserRows().find(x=>normalize(x.username)===username&&String(x.password)===password);if(!found)return{success:false,message:'Username atau password salah.'};const user=publicUser(found),token=Utilities.getUuid()+Utilities.getUuid();CacheService.getScriptCache().put('session:'+token,JSON.stringify(user),APP.SESSION_TTL_SECONDS);return{success:true,token,user};}
function validateToken(token){if(!token)return{valid:false};const c=CacheService.getScriptCache(),raw=c.get('session:'+token);if(!raw)return{valid:false};c.put('session:'+token,raw,APP.SESSION_TTL_SECONDS);return{valid:true,user:JSON.parse(raw)};}function logoutUser(token){if(token)CacheService.getScriptCache().remove('session:'+token);return{success:true};}function requireAdmin(u){if(!u||u.jabatan!=='Admin')throw new Error('Akses hanya untuk Admin.');}
function readUserRows(){const sh=getUserSheet(),n=sh.getLastRow();if(n<2)return[];return sh.getRange(2,1,n-1,5).getDisplayValues().map((r,i)=>({rowNumber:i+2,username:r[0],password:r[1],nama:r[2],jabatan:r[3],instansi:r[4]}));}
function getUsers(){return readUserRows().map(publicUser);}function getChatUsers(me){cleanupOldChats();const mine=normalize(me.username),users=readUserRows().filter(u=>normalize(u.username)!==mine),summary={};const sh=getChatSheet(),n=sh.getLastRow();if(n>=2){sh.getRange(2,1,n-1,6).getValues().forEach(r=>{const from=normalize(r[1]),to=normalize(r[2]);if(from!==mine&&to!==mine)return;const other=from===mine?to:from;if(!summary[other])summary[other]={unreadCount:0,lastMessage:'',lastTime:null};const time=new Date(r[4]);if(!summary[other].lastTime||time>summary[other].lastTime){summary[other].lastTime=time;summary[other].lastMessage=String(r[3]||'');}if(to===mine&&String(r[5]||'').trim().toLowerCase()!=='ya')summary[other].unreadCount++;});}return users.map(u=>{const x=summary[normalize(u.username)]||{};return Object.assign(publicUser(u),{unreadCount:Number(x.unreadCount||0),lastMessage:x.lastMessage||'',lastTime:x.lastTime?x.lastTime.toISOString():null});}).sort((a,b)=>{const ta=a.lastTime?new Date(a.lastTime).getTime():0,tb=b.lastTime?new Date(b.lastTime).getTime():0;return tb-ta||String(a.nama||a.username).localeCompare(String(b.nama||b.username),'id');});}
function addUser(r,actor){const username=normalize(r.username),password=String(r.password||''),nama=String(r.nama||'').trim(),jabatan=validRole(r.jabatan),instansi=String(r.instansi||'').trim();validateUserInput(username,password,nama,instansi,true);if(findUser(username))return{success:false,message:'Username sudah digunakan.'};getUserSheet().appendRow([username,password,nama,jabatan,instansi]);notifyAllExcept(actor.username,'user','User Baru','Akun '+nama+' telah ditambahkan.',username);return{success:true};}
function editUser(r,actor){const oldUsername=normalize(r.oldUsername),username=normalize(r.username),password=String(r.password||''),nama=String(r.nama||'').trim(),jabatan=validRole(r.jabatan),instansi=String(r.instansi||'').trim();validateUserInput(username,password,nama,instansi,false);const cur=findUser(oldUsername);if(!cur)return{success:false,message:'User tidak ditemukan.'};const dup=findUser(username);if(dup&&dup.rowNumber!==cur.rowNumber)return{success:false,message:'Username sudah digunakan.'};getUserSheet().getRange(cur.rowNumber,1,1,5).setValues([[username,password||cur.password,nama,jabatan,instansi]]);addNotification(username,'user','Data Akun Diperbarui','Data akun Anda telah diperbarui oleh admin.',username);return{success:true};}
function deleteUser(r,actor){const cur=findUser(normalize(r.username));if(!cur)return{success:false,message:'User tidak ditemukan.'};getUserSheet().deleteRow(cur.rowNumber);notifyAllExcept(actor.username,'user','User Dihapus','Akun '+cur.nama+' telah dihapus.',cur.username);return{success:true};}
function cleanupOldChats(){const sh=getChatSheet(),n=sh.getLastRow();if(n<2)return;const values=sh.getRange(2,1,n-1,6).getValues(),limit=Date.now()-APP.CHAT_TTL_MS;for(let i=values.length-1;i>=0;i--){const t=new Date(values[i][4]).getTime();if(!t||t<limit)sh.deleteRow(i+2);}}
function getChats(me,withUser){cleanupOldChats();const other=normalize(withUser),mine=normalize(me.username);if(!other)return{success:false,message:'Pilih pengguna chat.'};const sh=getChatSheet(),n=sh.getLastRow();if(n<2)return{success:true,messages:[]};const rows=sh.getRange(2,1,n-1,6).getValues(),readRows=[];const messages=[];rows.forEach((r,i)=>{const from=normalize(r[1]),to=normalize(r[2]);if((from===mine&&to===other)||(from===other&&to===mine)){messages.push({id:r[0],from:r[1],to:r[2],text:r[3],time:new Date(r[4]).toISOString(),type:from===mine?'outgoing':'incoming'});if(to===mine&&String(r[5]).toLowerCase()!=='ya')readRows.push(i+2);}});readRows.forEach(row=>sh.getRange(row,6).setValue('Ya'));return{success:true,messages};}
function sendChat(me,r){cleanupOldChats();const to=normalize(r.to),text=String(r.message||'').trim();if(!to||!text)throw new Error('Penerima dan pesan wajib diisi.');if(to===normalize(me.username))throw new Error('Tidak dapat mengirim pesan ke akun sendiri.');const target=findUser(to);if(!target)throw new Error('User penerima tidak ditemukan.');const id=Utilities.getUuid(),now=new Date();getChatSheet().appendRow([id,me.username,target.username,text,now,'Tidak']);addNotification(target.username,'chat','Pesan Baru dari '+(me.nama||me.username),text,me.username);return{success:true,id,time:now.toISOString()};}
function addNotification(username,type,title,message,ref){getNotificationSheet().appendRow([Utilities.getUuid(),normalize(username),type,title,message,new Date(),'Tidak',ref||'']);}
function notifyAllExcept(except,type,title,message,ref){readUserRows().forEach(u=>{if(normalize(u.username)!==normalize(except))addNotification(u.username,type,title,message,ref);});}
function getNotifications(me){const sh=getNotificationSheet(),n=sh.getLastRow();if(n<2)return{success:true,notifications:[]};const mine=normalize(me.username),rows=sh.getRange(2,1,n-1,8).getValues().filter(r=>normalize(r[1])===mine).map(r=>({id:r[0],type:r[2],title:r[3],message:r[4],time:new Date(r[5]).toISOString(),read:String(r[6]).toLowerCase()==='ya',reference:r[7]})).sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,50);return{success:true,notifications:rows};}
function markNotificationRead(me,id){const sh=getNotificationSheet(),n=sh.getLastRow(),mine=normalize(me.username);if(n<2)return{success:true};const rows=sh.getRange(2,1,n-1,8).getValues();rows.forEach((r,i)=>{if(String(r[0])===String(id)&&normalize(r[1])===mine)sh.getRange(i+2,7).setValue('Ya');});return{success:true};}
function markAllNotificationsRead(me){const sh=getNotificationSheet(),n=sh.getLastRow(),mine=normalize(me.username);if(n<2)return{success:true};const rows=sh.getRange(2,1,n-1,8).getValues();rows.forEach((r,i)=>{if(normalize(r[1])===mine)sh.getRange(i+2,7).setValue('Ya');});return{success:true};}
function findUser(username){return readUserRows().find(r=>normalize(r.username)===normalize(username))||null;}function validateUserInput(u,p,n,i,req){if(!u||!n||!i||(req&&!p))throw new Error('Data user belum lengkap.');if(p&&p.length<6)throw new Error('Password minimal 6 karakter.');}function validRole(v){const r=String(v||'').trim();if(['Admin','Validator','Operator'].indexOf(r)<0)throw new Error('Jabatan tidak valid.');return r;}function publicUser(u){return{username:u.username,nama:u.nama,jabatan:u.jabatan,instansi:u.instansi};}function normalize(v){return String(v||'').trim().toLowerCase();}function jsonResponse(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON);}
